package modelos;
// Generated 15-nov-2014 16:08:52 by Hibernate Tools 3.6.0


import java.util.Date;

/**
 * Diagnostico generated by hbm2java
 */
public class Diagnostico  implements java.io.Serializable {


     private Integer idDiagnostico;
     private Cita cita;
     private String diagnostico;
     private Date fechahora;

    public Diagnostico() {
    }

    public Diagnostico(Cita cita, String diagnostico, Date fechahora) {
       this.cita = cita;
       this.diagnostico = diagnostico;
       this.fechahora = fechahora;
    }
   
    public Integer getIdDiagnostico() {
        return this.idDiagnostico;
    }
    
    public void setIdDiagnostico(Integer idDiagnostico) {
        this.idDiagnostico = idDiagnostico;
    }
    public Cita getCita() {
        return this.cita;
    }
    
    public void setCita(Cita cita) {
        this.cita = cita;
    }
    public String getDiagnostico() {
        return this.diagnostico;
    }
    
    public void setDiagnostico(String diagnostico) {
        this.diagnostico = diagnostico;
    }
    public Date getFechahora() {
        return this.fechahora;
    }
    
    public void setFechahora(Date fechahora) {
        this.fechahora = fechahora;
    }




}


