package modelos;
// Generated 15-nov-2014 16:08:52 by Hibernate Tools 3.6.0


import java.util.HashSet;
import java.util.Set;

/**
 * Paciente generated by hbm2java
 */
public class Paciente  implements java.io.Serializable {


     private Integer idPaciente;
     private Usuario usuario;
     private Eps eps;
     private int cotizante;
     private String direccion;
     private String email;
     private String telefono;
     private Set citas = new HashSet(0);

    public Paciente() {
    }

	
    public Paciente(Usuario usuario, Eps eps, int cotizante, String direccion, String email, String telefono) {
        this.usuario = usuario;
        this.eps = eps;
        this.cotizante = cotizante;
        this.direccion = direccion;
        this.email = email;
        this.telefono = telefono;
    }
    public Paciente(Usuario usuario, Eps eps, int cotizante, String direccion, String email, String telefono, Set citas) {
       this.usuario = usuario;
       this.eps = eps;
       this.cotizante = cotizante;
       this.direccion = direccion;
       this.email = email;
       this.telefono = telefono;
       this.citas = citas;
    }
   
    public Integer getIdPaciente() {
        return this.idPaciente;
    }
    
    public void setIdPaciente(Integer idPaciente) {
        this.idPaciente = idPaciente;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public Eps getEps() {
        return this.eps;
    }
    
    public void setEps(Eps eps) {
        this.eps = eps;
    }
    public int getCotizante() {
        return this.cotizante;
    }
    
    public void setCotizante(int cotizante) {
        this.cotizante = cotizante;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getTelefono() {
        return this.telefono;
    }
    
    public void setTelefono(String telefono) {
        this.telefono = telefono;
    }
    public Set getCitas() {
        return this.citas;
    }
    
    public void setCitas(Set citas) {
        this.citas = citas;
    }




}


